name: Telegram AI Assistant
env:
     API_ID: ${{ secrets.API_ID }}
     API_HASH: ${{ secrets.API_HASH }}
     TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

run: python personal_ai.py

on:
  workflow_dispatch:

jobs:
  run-bot:

    runs-on: ubuntu-latest

    timeout-minutes: 350

    steps:

      - name: Download code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install packages
        run: |
          pip install -r requirements.txt


      - name: Start AI Assistant
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}

        run: |
          python personal_ai.py